class Constants:
    # Branching rule
    DEPTH_FIRST_NODE_SELECTION = 1
    BREADTH_FIRST_NODE_SELECTION = 2
    BEST_FIRST_NODE_SELECTION = 3

    # NODE SELECTION RULE
    VARIABLE_SELECTION_FIRST = 4
    VARIABLE_SELECTION_LAST = 5
    VARIABLE_SELECTION_MOST_FRACTIONAL = 6
    VARIABLE_SELECTION_LEAST_FRACTIONAL = 7
    OBJECTIVE_MINIMIZE = "min"
    OBJECTIVE_MAXIMIZE = "max"






